const { Authorize } = require('./src/controllers/authenticateController.js');

const swaggerAutogen = require('swagger-autogen')();
const swaggerFile = './swagger_output.json';

const endpointsFiles = [
  './src/app.js'
];

const doc = {
  info: {
    version: "1.0.0",
    title: "User Api",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3000",
  basePath: "",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  explorer: true,
  securityDefinitions: {
    Bearer: {
      type: "apiKey",
      name: "Authorization",
      in: "header"
    }
  },
  security: [
    {
      Bearer: []
    }
  ]
};

swaggerAutogen(swaggerFile, endpointsFiles, doc)
  .then(async () => {
    require('./src/app.js');
  })
  .catch((err) => logger.error(err));